In [38]:
import pandas as pd
import time
from concurrent.futures import ThreadPoolExecutor
import os
import random
import time
import urllib.error
import socket
import datetime
import requests
from bs4 import BeautifulSoup

In [22]:
def save_to_csv(df, filename):
    if not os.path.isfile(filename):
        df.to_csv(filename, index=False)
    else:  
        df.to_csv(filename, mode='a', header=False, index=False)

In [23]:
names_df = pd.read_csv(r"C:\Users\gabri\Documents\nhl_players_dataset.csv")

In [24]:
names_df.columns = ["Player Name", "Player Link", "Position", "Debut Year", "Final Year"]
names_df.head()

,Player Name,Player Link,Position,Debut Year,Final Year
0,George Abbott,/players/a/abbotge01.html,G,1944,1944
1,Reg Abbott,/players/a/abbotre01.html,C,1953,1953
2,Spencer Abbott,/players/a/abbotsp01.html,LW,2014,2017
3,Justin Abdelkader,/players/a/abdelju01.html,LW,2008,2020
4,Clarence Abel,/players/a/abelcl01.html,D,1927,1934

In [25]:
names_df['Total Years'] = (names_df['Final Year'] - names_df['Debut Year']) + 1
names_df

,Player Name,Player Link,Position,Debut Year,Final Year,Total Years
0,George Abbott,/players/a/abbotge01.html,G,1944,1944,1
1,Reg Abbott,/players/a/abbotre01.html,C,1953,1953,1
2,Spencer Abbott,/players/a/abbotsp01.html,LW,2014,2017,4
3,Justin Abdelkader,/players/a/abdelju01.html,LW,2008,2020,13
4,Clarence Abel,/players/a/abelcl01.html,D,1927,1934,8
...,...,...,...,...,...,...
8525,Jason Zucker,/players/z/zuckeja01.html,LW,2012,2024,13
8526,Mike Zuke,/players/z/zukemi01.html,C,1979,1986,8
8527,Rudy Zunich,/players/z/zunicru01.html,D,1944,1944,1
8528,Valentin Zykov,/players/z/zykovva01.html,LW,2017,2020,4
8529,Andrei Zyuzin,/players/z/zyuzian01.html,D,1998,2008,11

In [26]:
condition1 = ((names_df['Final Year'] != 2024) & (names_df['Total Years'] < 5)) | ((names_df['Final Year'] < 2008))
filtered_df = names_df[~condition1]
filtered_df

,Player Name,Player Link,Position,Debut Year,Final Year,Total Years
3,Justin Abdelkader,/players/a/abdelju01.html,LW,2008,2020,13
13,Noel Acciari,/players/a/acciano01.html,C,2016,2024,9
19,Luke Adam,/players/a/adamlu01.html,C,2011,2015,5
22,Craig Adams,/players/a/adamscr01.html,RW,2001,2015,15
28,Kevyn Adams,/players/a/adamske01.html,C,1998,2008,11
...,...,...,...,...,...,...
8522,Sergei Zubov,/players/z/zubovse01.html,D,1993,2009,17
8523,Dainius Zubrus,/players/z/zubruda01.html,RW/C,1997,2016,20
8524,Mats Zuccarello,/players/z/zuccama01.html,LW,2011,2024,14
8525,Jason Zucker,/players/z/zuckeja01.html,LW,2012,2024,13
8529,Andrei Zyuzin,/players/z/zyuzian01.html,D,1998,2008,11

In [27]:
df_goalies = filtered_df[filtered_df['Position'] == 'G']
df_goalies

,Player Name,Player Link,Position,Debut Year,Final Year,Total Years
32,David Aebischer,/players/a/aebisda01.html,G,2001,2008,8
77,Jake Allen,/players/a/allenja01.html,G,2013,2024,12
103,Frederik Andersen,/players/a/anderfr01.html,G,2014,2024,11
104,Craig Anderson,/players/a/andercr01.html,G,2003,2023,21
149,Justus Annunen,/players/a/annunju01.html,G,2022,2024,3
...,...,...,...,...,...,...
8160,Cam Ward,/players/w/wardca01.html,G,2006,2019,14
8208,Scott Wedgewood,/players/w/wedgesc01.html,G,2016,2024,9
8211,Kevin Weekes,/players/w/weekeke01.html,G,1998,2009,12
8377,Dustin Wolf,/players/w/wolfdu01.html,G,2023,2024,2
8379,Joseph Woll,/players/w/wolljo01.html,G,2022,2024,3

In [28]:
df_players = filtered_df[filtered_df['Position'] != 'G']
df_players

,Player Name,Player Link,Position,Debut Year,Final Year,Total Years
3,Justin Abdelkader,/players/a/abdelju01.html,LW,2008,2020,13
13,Noel Acciari,/players/a/acciano01.html,C,2016,2024,9
19,Luke Adam,/players/a/adamlu01.html,C,2011,2015,5
22,Craig Adams,/players/a/adamscr01.html,RW,2001,2015,15
28,Kevyn Adams,/players/a/adamske01.html,C,1998,2008,11
...,...,...,...,...,...,...
8522,Sergei Zubov,/players/z/zubovse01.html,D,1993,2009,17
8523,Dainius Zubrus,/players/z/zubruda01.html,RW/C,1997,2016,20
8524,Mats Zuccarello,/players/z/zuccama01.html,LW,2011,2024,14
8525,Jason Zucker,/players/z/zuckeja01.html,LW,2012,2024,13
8529,Andrei Zyuzin,/players/z/zyuzian01.html,D,1998,2008,11

In [29]:
player_name_list = df_players['Player Name'].tolist()
player_link_list = df_players['Player Link'].tolist()

In [30]:
full_df_players_list = []
batch_size = 200

def fetch_html_with_retry(url, retries=3, delay=50):
    """Fetch HTML content with retries in case of network errors."""
    for i in range(retries):
        try:
            full_df = pd.read_html(url)
            return full_df
        except (urllib.error.URLError, socket.gaierror) as e:
            print(f"Attempt {i+1} failed: {e}")
            time.sleep(delay)
    raise Exception(f"Failed to retrieve data from {url} after {retries} attempts")

for batch_start in range(0, len(player_link_list), batch_size):
    batch = player_link_list[batch_start:batch_start + batch_size]
    for players in batch:  # Corrected to iterate over the batch
        url = f"https://www.hockey-reference.com{players}"
        try:
            full_df = fetch_html_with_retry(url)
            player_df = full_df[8]
            player_df['Player Links'] = players
            player_df['Situation'] = 'All'
            full_df_players_list.append(player_df)
            time.sleep(1)

            player_df2 = full_df[9]
            player_df2['Player Links'] = players
            player_df2['Situation'] = 'Even Strength'
            full_df_players_list.append(player_df2)
            time.sleep(1)

            player_df3 = full_df[10]
            player_df3['Player Links'] = players
            player_df3['Situation'] = 'Power Play'
            full_df_players_list.append(player_df3)
            time.sleep(1)

            player_df4 = full_df[11]
            player_df4['Player Links'] = players
            player_df4['Situation'] = 'Short-Handed'
            full_df_players_list.append(player_df4)
            time.sleep(1)

            player_df5 = full_df[12]
            player_df5['Player Links'] = players
            player_df5['Situation'] = '5-On-5'
            full_df_players_list.append(player_df5)
            time.sleep(1)

            player_df6 = full_df[13]
            player_df6['Player Links'] = players
            player_df6['Situation'] = '5-On-5 Close'
            full_df_players_list.append(player_df6)
            time.sleep(1)

            player_df7 = full_df[14]
            player_df7['Player Links'] = players
            player_df7['Situation'] = '5-On-5 Tied'
            full_df_players_list.append(player_df7)
            time.sleep(1)

        except Exception as e:
            print(f"Skipping {url} due to repeated failures.")

    time.sleep(random.randint(100, 220))  # Longer delay between batches

full_df_players = pd.concat(full_df_players_list, ignore_index=True)

Attempt 1 failed: <urlopen error [Errno 11001] getaddrinfo failed>
Attempt 1 failed: <urlopen error [Errno 11001] getaddrinfo failed>
Attempt 1 failed: <urlopen error [Errno 11001] getaddrinfo failed>

In [31]:
full_df_players.head(30)

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0
               Season                Age               Team
0             2007-08               20.0                DET  \
1             2008-09               21.0                DET
2             2009-10               22.0                DET
3             2010-11               23.0                DET
4             2011-12               24.0                DET
5             2012-13               25.0                DET
6             2013-14               26.0                DET
7             2014-15               27.0                DET
8             2015-16               28.0                DET
9             2016-17               29.0                DET
10            2017-18               30.0                DET
11            2018-19               31.0                DET
12            2019-20               32.0                DET
13             Career                NaN                NaN
14            2007-08               20.0                DET
15            2008-09               21.0                DET
16            2009-10               22.0                DET
17            2010-11               23.0                DET
18            2011-12               24.0                DET
19            2012-13               25.0                DET
20            2013-14               26.0                DET
21            2014-15               27.0                DET
22            2015-16               28.0                DET
23            2016-17               29.0                DET
24            2017-18               30.0                DET
25            2018-19               31.0                DET
26            2019-20               32.0                DET
27             Career                NaN                NaN
28            2007-08               20.0                DET
29            2008-09               21.0                DET

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Corsi (All)
                   Lg                 GP                TOI          CF
0                 NHL                  2               24.4        19.0  \
1                 NHL                  2               18.6        22.0
2                 NHL                 50              529.6       457.0
3                 NHL                 74              910.2       801.0
4                 NHL                 81              997.5       823.0
5                 NHL                 48              711.0       684.0
6                 NHL                 70                NaN       944.0
7                 NHL                 71             1271.6      1260.0
8                 NHL                 82             1511.7      1402.0
9                 NHL                 64             1065.8       935.0
10                NHL                 75             1241.3      1193.0
11                NHL                 71             1092.7       868.0
12                NHL                 49              565.2       399.0
13                NHL                739             9939.5      9807.0
14                NHL                  2               23.0         NaN
15                NHL                  2               18.6         NaN
16                NHL                 50              480.2         NaN
17                NHL                 74              771.8         NaN
18                NHL                 81              871.9         NaN
19                NHL                 48              654.7         NaN
20                NHL                 70                NaN         NaN
21                NHL                 71             1006.2         NaN
22                NHL                 82             1138.6         NaN
23                NHL                 64              839.3         NaN
24                NHL                 75              961.6         NaN
25                NHL                 71              916.2         NaN
26                NHL                 49              480.1         NaN
27                NHL                739             8162.1         NaN
28                NHL                  2                0.0         NaN
29                NHL                  2                0.0         NaN

                          ... Fenwick (5v5 tied)             PDO (5v5 tied)
        CA   CF% CF% rel  ...                 FA FF% FF% rel           oiGF
0     19.0  50.0   -14.2  ...                NaN NaN     NaN            NaN  \
1      9.0  71.0    23.3  ...                NaN NaN     NaN            NaN
2    397.0  53.5    -2.5  ...                NaN NaN     NaN            NaN
3    827.0  49.2    -7.8  ...                NaN NaN     NaN            NaN
4    882.0  48.3    -9.0  ...                NaN NaN     NaN            NaN
5    536.0  56.1     3.1  ...                NaN NaN     NaN            NaN
6    883.0  51.7    -0.8  ...                NaN NaN     NaN            NaN
7    855.0  59.6     9.8  ...                NaN NaN     NaN            NaN
8   1235.0  53.2     2.7  ...                NaN NaN     NaN            NaN
9    934.0  50.0     2.7  ...                NaN NaN     NaN            NaN
10  1111.0  51.8     4.2  ...                NaN NaN     NaN            NaN
11  1132.0  43.4    -5.6  ...                NaN NaN     NaN            NaN
12   526.0  43.1    -2.8  ...                NaN NaN     NaN            NaN
13  9346.0  51.2     0.7  ...                NaN NaN     NaN            NaN
14     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
15     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
16     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
17     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
18     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
19     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
20     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
21     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
22     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
23     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
24     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
25     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
26     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
27     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
28     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN
29     NaN   NaN     NaN  ...                NaN NaN     NaN            NaN

                        Zone Starts (5v5 tied)
   oiSH% oiGA oiSV% PDO                   oZS% dZS%
0    NaN  NaN   NaN NaN                    NaN  NaN
1    NaN  NaN   NaN NaN                    NaN  NaN
2    NaN  NaN   NaN NaN                    NaN  NaN
3    NaN  NaN   NaN NaN                    NaN  NaN
4    NaN  NaN   NaN NaN                    NaN  NaN
5    NaN  NaN   NaN NaN                    NaN  NaN
6    NaN  NaN   NaN NaN                    NaN  NaN
7    NaN  NaN   NaN NaN                    NaN  NaN
8    NaN  NaN   NaN NaN                    NaN  NaN
9    NaN  NaN   NaN NaN                    NaN  NaN
10   NaN  NaN   NaN NaN                    NaN  NaN
11   NaN  NaN   NaN NaN                    NaN  NaN
12   NaN  NaN   NaN NaN                    NaN  NaN
13   NaN  NaN   NaN NaN                    NaN  NaN
14   NaN  NaN   NaN NaN                    NaN  NaN
15   NaN  NaN   NaN NaN                    NaN  NaN
16   NaN  NaN   NaN NaN                    NaN  NaN
17   NaN  NaN   NaN NaN                    NaN  NaN
18   NaN  NaN   NaN NaN                    NaN  NaN
19   NaN  NaN   NaN NaN                    NaN  NaN
20   NaN  NaN   NaN NaN                    NaN  NaN
21   NaN  NaN   NaN NaN                    NaN  NaN
22   NaN  NaN   NaN NaN                    NaN  NaN
23   NaN  NaN   NaN NaN                    NaN  NaN
24   NaN  NaN   NaN NaN                    NaN  NaN
25   NaN  NaN   NaN NaN                    NaN  NaN
26   NaN  NaN   NaN NaN                    NaN  NaN
27   NaN  NaN   NaN NaN                    NaN  NaN
28   NaN  NaN   NaN NaN                    NaN  NaN
29   NaN  NaN   NaN NaN                    NaN  NaN

[30 rows x 113 columns]

In [32]:
player_advanced_stats_data = r"C:\Users\gabri\Documents\player_advanced_stats_dataset.csv"
save_to_csv(full_df_players, player_advanced_stats_data)